#\u6240\u6709\u670D\u52A1\u90FD\u9700\u8981\u5411\u670D\u52A1\u4E2D\u5FC3Eureka\u8FDB\u884C\u6CE8\u518C
eureka:
  client:
    serviceUrl:
      #默认地址http://localhost:8761/eureka/
      defaultZone: http://localhost:8080/eureka/
#\u8BBE\u7F6E\u7AEF\u53E3\u53F7
server:
  port: 8085
#\u670D\u52A1\u540D\u79F0
spring:
  application:
    name: service-feign

#\u5F00\u542Fhystrix\u65AD\u8DEF\u5668
feign:
  hystrix:
    enabled: true